In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from sklearn.metrics import confusion_matrix
import os

Using TensorFlow backend.


In [2]:
os.chdir('C:\\Users\\shaik shoyab\\Desktop\\Data_Science\\Datasets')

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')


In [4]:
X = dataset.iloc[:, 3:13].values

y = dataset.iloc[:, 13].values

In [5]:
labelencoder_X_1 = LabelEncoder()
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

X.shape

(10000, 10)

In [8]:
tmpDF = pd.DataFrame(X)
tmpDF

0  1  2   3   4        5  6  7  8        9
0     619  0  0  42   2        0  1  1  1   101349
1     608  2  0  41   1  83807.9  1  0  1   112543
2     502  0  0  42   8   159661  3  1  0   113932
3     699  0  0  39   1        0  2  0  0  93826.6
4     850  2  0  43   2   125511  1  1  1  79084.1
5     645  2  1  44   8   113756  2  1  0   149757
6     822  0  1  50   7        0  2  1  1  10062.8
7     376  1  0  29   4   115047  4  1  0   119347
8     501  0  1  44   4   142051  2  0  1  74940.5
9     684  0  1  27   2   134604  1  1  1  71725.7
10    528  0  1  31   6   102017  2  0  0  80181.1
11    497  2  1  24   3        0  2  1  0    76390
12    476  0  0  34  10        0  2  1  0    26261
13    549  0  0  25   5        0  2  0  0   190858
14    635  2  0  35   7        0  2  1  1  65951.6
15    616  1  1  45   3   143129  2  0  1  64327.3
16    653  1  1  58   1   132603  1  1  0  5097.67
17    549  2  0  24   9        0  2  1  1  14406.4
18    587  2  1  45   6        0  1  0  0   158685
19    726  0  0  24   6        0  2  1  1    54724
20    732  0  1  41   8        0  2  1  1   170886
21    636  2  0  32   8        0  2  1  0   138555
22    510  2  0  38   4        0  1  1  0   118914
23    669  0  1  46   3        0  2  0  1  8487.75
24    846  0  0  38   5        0  1  1  1   187616
25    577  0  1  25   3        0  2  0  1   124508
26    756  1  1  36   2   136816  1  1  1   170042
27    571  0  1  44   9        0  2  0  0  38433.3
28    574  1  0  43   3   141349  1  1  1   100187
29    411  0  1  29   0  59697.2  2  1  1  53483.2
...   ... .. ..  ..  ..      ... .. .. ..      ...
9970  518  0  1  42   7   151027  2  1  0   119377
9971  833  0  0  34   3   144752  1  0  0   166473
9972  758  0  1  26   4   155740  1  1  0   171552
9973  611  0  1  27   7        0  2  1  1   157474
9974  583  0  1  33   7   122532  1  1  0  13549.2
9975  610  1  1  50   1   113957  2  1  0   196527
9976  637  0  0  33   7   103378  1  1  0  84419.8
9977  683  0  0  32   9        0  2  1  1  24991.9
9978  774  0  1  40   9  93017.5  2  1  0   191609
9979  677  0  0  58   1  90022.9  1  0  1  2988.28
9980  741  2  1  35   6  74371.5  1  0  0  99595.7
9981  498  1  1  42   3   152040  1  1  1  53445.2
9982  655  1  0  46   7   137145  1  1  0   115146
9983  613  0  1  40   4        0  1  0  0   151325
9984  602  1  1  35   7  90602.4  2  1  1  51695.4
9985  659  0  1  36   6   123841  2  1  0    96833
9986  673  1  1  47   1   183580  2  0  1  34047.5
9987  606  2  1  30   8   180308  2  1  1  1914.41
9988  775  0  1  30   4        0  2  1  0  49337.8
9989  841  2  1  28   4        0  2  1  1   179437
9990  714  1  1  33   3  35016.6  1  1  0  53667.1
9991  597  0  0  53   4  88381.2  1  1  0  69384.7
9992  726  2  1  36   2        0  1  1  0   195192
9993  644  0  1  28   7   155060  1  1  0  29179.5
9994  800  0  0  29   2        0  2  0  0   167774
9995  771  0  1  39   5        0  2  1  0  96270.6
9996  516  0  1  35  10  57369.6  1  1  1   101700
9997  709  0  0  36   7        0  1  0  1  42085.6
9998  772  1  1  42   3  75075.3  2  1  0  92888.5
9999  792  0  0  28   4   130143  1  1  0  38190.8

[10000 rows x 10 columns]

In [9]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X

C:\Users\shaik shoyab\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\shaik shoyab\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [10]:
tmpDF = pd.DataFrame(X)
tmpDF

0    1    2      3    4     5     6          7    8    9    10  \
0     1.0  0.0  0.0  619.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0   
1     0.0  0.0  1.0  608.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0   
2     1.0  0.0  0.0  502.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0   
3     1.0  0.0  0.0  699.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   
4     0.0  0.0  1.0  850.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   
5     0.0  0.0  1.0  645.0  1.0  44.0   8.0  113755.78  2.0  1.0  0.0   
6     1.0  0.0  0.0  822.0  1.0  50.0   7.0       0.00  2.0  1.0  1.0   
7     0.0  1.0  0.0  376.0  0.0  29.0   4.0  115046.74  4.0  1.0  0.0   
8     1.0  0.0  0.0  501.0  1.0  44.0   4.0  142051.07  2.0  0.0  1.0   
9     1.0  0.0  0.0  684.0  1.0  27.0   2.0  134603.88  1.0  1.0  1.0   
10    1.0  0.0  0.0  528.0  1.0  31.0   6.0  102016.72  2.0  0.0  0.0   
11    0.0  0.0  1.0  497.0  1.0  24.0   3.0       0.00  2.0  1.0  0.0   
12    1.0  0.0  0.0  476.0  0.0  34.0  10.0       0.00  2.0  1.0  0.0   
13    1.0  0.0  0.0  549.0  0.0  25.0   5.0       0.00  2.0  0.0  0.0   
14    0.0  0.0  1.0  635.0  0.0  35.0   7.0       0.00  2.0  1.0  1.0   
15    0.0  1.0  0.0  616.0  1.0  45.0   3.0  143129.41  2.0  0.0  1.0   
16    0.0  1.0  0.0  653.0  1.0  58.0   1.0  132602.88  1.0  1.0  0.0   
17    0.0  0.0  1.0  549.0  0.0  24.0   9.0       0.00  2.0  1.0  1.0   
18    0.0  0.0  1.0  587.0  1.0  45.0   6.0       0.00  1.0  0.0  0.0   
19    1.0  0.0  0.0  726.0  0.0  24.0   6.0       0.00  2.0  1.0  1.0   
20    1.0  0.0  0.0  732.0  1.0  41.0   8.0       0.00  2.0  1.0  1.0   
21    0.0  0.0  1.0  636.0  0.0  32.0   8.0       0.00  2.0  1.0  0.0   
22    0.0  0.0  1.0  510.0  0.0  38.0   4.0       0.00  1.0  1.0  0.0   
23    1.0  0.0  0.0  669.0  1.0  46.0   3.0       0.00  2.0  0.0  1.0   
24    1.0  0.0  0.0  846.0  0.0  38.0   5.0       0.00  1.0  1.0  1.0   
25    1.0  0.0  0.0  577.0  1.0  25.0   3.0       0.00  2.0  0.0  1.0   
26    0.0  1.0  0.0  756.0  1.0  36.0   2.0  136815.64  1.0  1.0  1.0   
27    1.0  0.0  0.0  571.0  1.0  44.0   9.0       0.00  2.0  0.0  0.0   
28    0.0  1.0  0.0  574.0  0.0  43.0   3.0  141349.43  1.0  1.0  1.0   
29    1.0  0.0  0.0  411.0  1.0  29.0   0.0   59697.17  2.0  1.0  1.0   
...   ...  ...  ...    ...  ...   ...   ...        ...  ...  ...  ...   
9970  1.0  0.0  0.0  518.0  1.0  42.0   7.0  151027.05  2.0  1.0  0.0   
9971  1.0  0.0  0.0  833.0  0.0  34.0   3.0  144751.81  1.0  0.0  0.0   
9972  1.0  0.0  0.0  758.0  1.0  26.0   4.0  155739.76  1.0  1.0  0.0   
9973  1.0  0.0  0.0  611.0  1.0  27.0   7.0       0.00  2.0  1.0  1.0   
9974  1.0  0.0  0.0  583.0  1.0  33.0   7.0  122531.86  1.0  1.0  0.0   
9975  0.0  1.0  0.0  610.0  1.0  50.0   1.0  113957.01  2.0  1.0  0.0   
9976  1.0  0.0  0.0  637.0  0.0  33.0   7.0  103377.81  1.0  1.0  0.0   
9977  1.0  0.0  0.0  683.0  0.0  32.0   9.0       0.00  2.0  1.0  1.0   
9978  1.0  0.0  0.0  774.0  1.0  40.0   9.0   93017.47  2.0  1.0  0.0   
9979  1.0  0.0  0.0  677.0  0.0  58.0   1.0   90022.85  1.0  0.0  1.0   
9980  0.0  0.0  1.0  741.0  1.0  35.0   6.0   74371.49  1.0  0.0  0.0   
9981  0.0  1.0  0.0  498.0  1.0  42.0   3.0  152039.70  1.0  1.0  1.0   
9982  0.0  1.0  0.0  655.0  0.0  46.0   7.0  137145.12  1.0  1.0  0.0   
9983  1.0  0.0  0.0  613.0  1.0  40.0   4.0       0.00  1.0  0.0  0.0   
9984  0.0  1.0  0.0  602.0  1.0  35.0   7.0   90602.42  2.0  1.0  1.0   
9985  1.0  0.0  0.0  659.0  1.0  36.0   6.0  123841.49  2.0  1.0  0.0   
9986  0.0  1.0  0.0  673.0  1.0  47.0   1.0  183579.54  2.0  0.0  1.0   
9987  0.0  0.0  1.0  606.0  1.0  30.0   8.0  180307.73  2.0  1.0  1.0   
9988  1.0  0.0  0.0  775.0  1.0  30.0   4.0       0.00  2.0  1.0  0.0   
9989  0.0  0.0  1.0  841.0  1.0  28.0   4.0       0.00  2.0  1.0  1.0   
9990  0.0  1.0  0.0  714.0  1.0  33.0   3.0   35016.60  1.0  1.0  0.0   
9991  1.0  0.0  0.0  597.0  0.0  53.0   4.0   88381.21  1.0  1.0  0.0   
9992  0.0  0.0  1.0  726.0  1.0  36.0   2.0       0.00  1.0  1.0 

In [11]:
X.shape

(10000, 12)

In [12]:
X = X[:, 1:]
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [13]:
X.shape

(10000, 11)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [16]:
X_train = sc.fit_transform(X_train)

X_test = sc.transform(X_test)


In [17]:
classifier = Sequential()

W0203 20:05:39.270739  2852 deprecation_wrapper.py:119] From C:\Users\shaik shoyab\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [18]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

W0203 20:05:39.380546  2852 deprecation_wrapper.py:119] From C:\Users\shaik shoyab\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0203 20:05:39.385539  2852 deprecation_wrapper.py:119] From C:\Users\shaik shoyab\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [19]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [20]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

W0203 20:05:39.628638  2852 deprecation_wrapper.py:119] From C:\Users\shaik shoyab\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0203 20:05:39.695617  2852 deprecation_wrapper.py:119] From C:\Users\shaik shoyab\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0203 20:05:39.703594  2852 deprecation.py:323] From C:\Users\shaik shoyab\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [21]:
history = classifier.fit(X_train, y_train, batch_size = 10, epochs = 10)

W0203 20:05:39.969460  2852 deprecation_wrapper.py:119] From C:\Users\shaik shoyab\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/10
8000/8000 [==============================] - 3s 370us/step - loss: 0.4827 - acc: 0.7955
Epoch 2/10
8000/8000 [==============================] - 1s 169us/step - loss: 0.4285 - acc: 0.7960
Epoch 3/10
8000/8000 [==============================] - 2s 232us/step - loss: 0.4232 - acc: 0.7960
Epoch 4/10
8000/8000 [==============================] - 2s 233us/step - loss: 0.4191 - acc: 0.8147
Epoch 5/10
8000/8000 [==============================] - 2s 240us/step - loss: 0.4169 - acc: 0.8261
Epoch 6/10
8000/8000 [==============================] - 1s 155us/step - loss: 0.4151 - acc: 0.8292
Epoch 7/10
8000/8000 [==============================] - 1s 155us/step - loss: 0.4130 - acc: 0.8309
Epoch 8/10
8000/8000 [==============================] - 1s 171us/step - loss: 0.4127 - acc: 0.8316
Epoch 9/10
8000/8000 [==============================] - 2s 190us/step - loss: 0.4114 - acc: 0.8309
Epoch 10/10
8000/8000 [==============================] - 2s 234us/step - loss: 0.4105 - acc: 0.8332


In [22]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [23]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [24]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1560   35]
 [ 291  114]]


In [25]:
score = classifier.evaluate(X_test,y_test)
print(score)
print('loss = ', score[0])
print('acc = ', score[1])

2000/2000 [==============================] - 0s 87us/step
[0.4048534016609192, 0.837]
loss =  0.4048534016609192
acc =  0.837


In [26]:
#Now increase the accuracy

In [27]:
classifier = Sequential()
classifier.add(Dense(units = 20, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 20, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [28]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [29]:
history = classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
8000/8000 [==============================] - 3s 330us/step - loss: 0.4664 - acc: 0.7955
Epoch 2/20
8000/8000 [==============================] - 2s 238us/step - loss: 0.4238 - acc: 0.8011
Epoch 3/20
8000/8000 [==============================] - 2s 242us/step - loss: 0.4179 - acc: 0.8239
Epoch 4/20
8000/8000 [==============================] - 2s 254us/step - loss: 0.4154 - acc: 0.8289
Epoch 5/20
8000/8000 [==============================] - 2s 230us/step - loss: 0.4130 - acc: 0.8319
Epoch 6/20
8000/8000 [==============================] - 2s 206us/step - loss: 0.4113 - acc: 0.8332
Epoch 7/20
8000/8000 [==============================] - 2s 197us/step - loss: 0.4083 - acc: 0.8339
Epoch 8/20
8000/8000 [==============================] - 2s 224us/step - loss: 0.4039 - acc: 0.8367
Epoch 9/20
8000/8000 [==============================] - 1s 169us/step - loss: 0.4017 - acc: 0.8359
Epoch 10/20
8000/8000 [==============================] - 1s 174us/step - loss: 0.3993 - acc: 0.8355
Epoch 11/

In [30]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [31]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1403  192]
 [ 158  247]]


In [32]:
score = classifier.evaluate(X_test,y_test)
print(score)
print('loss = ', score[0])
print('acc = ', score[1])

2000/2000 [==============================] - 0s 82us/step
[0.39258073234558105, 0.825]
loss =  0.39258073234558105
acc =  0.825


In [33]:
# Neurons
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [34]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1403  192]
 [ 158  247]]


In [35]:
score = classifier.evaluate(X_test,y_test)
print(score)
print('loss = ', score[0])
print('acc = ', score[1])

2000/2000 [==============================] - 0s 41us/step
[0.39258073234558105, 0.825]
loss =  0.39258073234558105
acc =  0.825
